In [1]:
import pandas as pd
import openpyxl
import f_stats_fig as fsf
import os
#from datamining import f_stats_fig as fsf

Que pasa mano?

In [3]:
#Caminho do arquivo (No caso Excel)
caminho_arquivo = r'C:\Users\DELL\anaconda3\envs\datamining\project\data\serie_temporal.xlsx'

#Para salvar as figuras automaticamente criaremos uma variável caminho_salva
caminho_salva = r'C:\Users\DELL\anaconda3\envs\datamining\project\data\figuras_datamining'
if not os.path.exists(caminho_salva):
    os.makedirs(caminho_salva)

#Lê o dataframe em formato excel
#df = pd.read_excel(io=caminho_arquivo,sheet_name="Planilha1",header=0,usecols="A:Q",engine='openpyxl')

df = fsf.leitura_xls(caminho_arquivo, "Planilha1", "A:Q")

df.columns = df.columns.str.strip() #Retira strings vazias dos dados
print(df.dtypes)
print(df.describe)
df

Data    datetime64[ns]
P1             float64
P2             float64
P3             float64
P4             float64
P5             float64
P6             float64
P7             float64
P8             float64
P9             float64
P10            float64
P11            float64
P12            float64
P13            float64
P14            float64
P15            float64
P16              int64
dtype: object
<bound method NDFrame.describe of          Data     P1     P2     P3     P4     P5     P6     P7     P8     P9  \
0  2012-01-01  251.7  378.4  384.8  264.8  284.7  296.2  241.8  428.9  540.2
1  2012-02-01   15.9   45.1  120.7  102.2  121.7  101.8   90.4   21.3  171.5
2  2012-03-01   84.4  170.4  131.6  152.5   56.6  163.7  121.3  192.7   77.5
3  2012-04-01   45.3   31.9   79.3  110.7   73.3   86.5   61.7   63.0   87.2
4  2012-05-01  101.0  118.1   72.4  111.3   48.1   64.4   47.4  184.8  140.9
..        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
91 2019-08-01   12.0   12.9    9.1  119.8   14.5    8.7    8.1   32.3   47.5
92 2019-09-01   37.2   32.5    9.1  157.6   51.6   52.6   67.9   35.7   73.2
93 2019-10-01   17.3   33.9   32.2   72.0   37.2   79.3   99.4  104.3   83.8
94 2019-11-01  230.6  209.1  211.8  211.3  127.4   85.4   67.1  290.8  332.8
95 2019-12-01  163.6  297.4  294.5  173.8  122.7  235.0  173.0  260.9  430.4

      P10    P11    P12    P13   P14    P15  P16
0   385.0  393.6  516.1  292.5  83.1  230.1  534
1   106.8   80.4   60.1   32.6  35.2  383.1  299
2   203.7  124.1  152.2  113.8  22.6   52.8  236
3   115.5   58.4   93.9   19.5  12.9   27.1  217
4   130.2   86.9   97.1  100.5  13.1   26.6  224
..    ...    ...    ...    ...   ...    ...  ...
91   49.4   30.3   19.2   18.4  30.3  140.3  116
92  100.0  157.6   96.3   45.8   3.5   91.4  118
93  173.8   35.6  109.8    6.3  27.6  110.8  116
94  190.9  139.2  387.9  195.2  49.3   66.5  150
95  228.2  134.5  381.0  239.4  67.5  450.7  267

[96 rows x 17 columns]>

,Data,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16
0,2012-01-01,251.7,378.4,384.8,264.8,284.7,296.2,241.8,428.9,540.2,385.0,393.6,516.1,292.5,83.1,230.1,534
1,2012-02-01,15.9,45.1,120.7,102.2,121.7,101.8,90.4,21.3,171.5,106.8,80.4,60.1,32.6,35.2,383.1,299
2,2012-03-01,84.4,170.4,131.6,152.5,56.6,163.7,121.3,192.7,77.5,203.7,124.1,152.2,113.8,22.6,52.8,236
3,2012-04-01,45.3,31.9,79.3,110.7,73.3,86.5,61.7,63.0,87.2,115.5,58.4,93.9,19.5,12.9,27.1,217
4,2012-05-01,101.0,118.1,72.4,111.3,48.1,64.4,47.4,184.8,140.9,130.2,86.9,97.1,100.5,13.1,26.6,224
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,2019-08-01,12.0,12.9,9.1,119.8,14.5,8.7,8.1,32.3,47.5,49.4,30.3,19.2,18.4,30.3,140.3,116
92,2019-09-01,37.2,32.5,9.1,157.6,51.6,52.6,67.9,35.7,73.2,100.0,157.6,96.3,45.8,3.5,91.4,118
93,2019-10-01,17.3,33.9,32.2,72.0,37.2,79.3,99.4,104.3,83.8,173.8,35.6,109.8,6.3,27.6,110.8,116
94,2019-11-01,230.6,209.1,211.8,211.3,127.4,85.4,67.1,290.8,332.8,190.9,139.2,387.9,195.2,49.3,66.5,150
95,2019-12-01,163.6,297.4,294.5,173.8,122.7,235.0,173.0,260.9,430.4,228.2,134.5,381.0,239.4,67.5,450.7,267

In [2]:
x = fsf.teste("celso")
x

True